apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: the-lab
  namespace: argocd
spec:
  destination:
    namespace: homelab
    server: https://kubernetes.default.svc
  project: default
  source:
    path: manifests
    repoURL: https://github.com/chadjvw/homelab.git
    targetRevision: HEAD
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  namespace: argocd
spec:
  destination:
    namespace: metallb-system
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: metallb
    helm:
      releaseName: metallb
    repoURL: https://metallb.github.io/metallb
    targetRevision: ~0.13.12
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
