apiVersion: v1
kind: Namespace
metadata:
  labels:
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/warn: privileged
  name: metallb-system
spec: {}
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: k3s-helm-charts-helm-chart-c85ae4e0
  namespace: kube-system
spec:
  chart: metallb
  repo: https://metallb.github.io/metallb
  targetNamespace: metallb-system
  version: ~0.13.12
