apiVersion: v1
kind: Namespace
metadata:
  labels:
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/warn: privileged
  name: metallb-system
spec: {}
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: metallb-helm-chart-c89d2eaf
  namespace: kube-system
spec:
  chart: metallb
  repo: https://metallb.github.io/metallb
  targetNamespace: metallb-system
  version: ~0.13.12
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: metallb-ip-pool-c8e59864
  namespace: metallb-system
spec:
  addresses:
    - 10.0.2.0-10.0.2.50
  avoidBuggyIPs: true
---
apiVersion: metallb.io/v1beta2
kind: BGPPeer
metadata:
  name: metallb-bgp-peer-c8b4bed3
  namespace: metallb-system
spec:
  myASN: 64500
  peerASN: 64501
  peerAddress: 10.0.0.1
